-- =========================================
-- Kloset Inventory Management Database Schema
-- =========================================
--
-- This schema provides a complete inventory management system with:
-- - User profiles linked to Supabase Auth
-- - Inventory items with AI-generated analysis
-- - Marketplace analytics for multiple platforms
-- - Saved analyses for historical tracking
-- - Row Level Security for data isolation
-- - Storage integration for item images
-- - Performance indexes and realtime support
--
-- Tables: profiles, inventory_items, marketplace_analytics, saved_analyses
-- Security: RLS enabled, user-scoped data access
-- Storage: inventory-images bucket with user-scoped access
-- =========================================

-- Enable Row Level Security
alter table if exists profiles enable row level security;
alter table if exists inventory_items enable row level security;
alter table if exists marketplace_analytics enable row level security;
alter table if exists saved_analyses enable row level security;

-- Create profiles table
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text unique,
  avatar_url text,
  created_at timestamptz default now()
);

-- Create inventory_items table
create table if not exists inventory_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  image_url text,
  item_name text not null check (length(item_name) > 0),
  brand text not null check (length(brand) > 0),
  category text not null check (length(category) > 0),
  color text,
  condition text not null check (condition in ('New', 'Like New', 'Good', 'Fair', 'Poor')),
  estimated_price numeric check (estimated_price >= 0),
  price_low numeric check (price_low >= 0),
  price_high numeric check (price_high >= 0),
  demand_score integer default 0 check (demand_score >= 0 and demand_score <= 100),
  marketplace_data jsonb default '{}',
  generated_title text,
  generated_description text,
  tags text[] default '{}',
  status text not null default 'Draft' check (status in ('Draft', 'Listed', 'Sold', 'Archived')),
  created_at timestamptz default now()
);

-- Create marketplace_analytics table
create table if not exists marketplace_analytics (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint references inventory_items(id) on delete cascade not null,
  platform text not null check (length(platform) > 0),
  estimated_sale_price numeric check (estimated_sale_price >= 0),
  estimated_sell_speed text check (estimated_sell_speed in ('Very Fast', 'Fast', 'Moderate', 'Slow', 'Very Slow')),
  fee_estimate numeric check (fee_estimate >= 0),
  demand_rating text check (demand_rating in ('Very High', 'High', 'Medium', 'Low', 'Very Low')),
  created_at timestamptz default now(),
  unique(inventory_item_id, platform) -- Ensure only one analytics record per item-platform combination
);

-- Create saved_analyses table
create table if not exists saved_analyses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  raw_analysis jsonb not null,
  created_at timestamptz default now()
);

-- Create storage bucket for inventory images
insert into storage.buckets (id, name, public)
values ('inventory-images', 'inventory-images', true)
on conflict (id) do nothing;

-- Row Level Security Policies

-- Profiles policies
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on profiles
  for insert with check (auth.uid() = id);

-- Inventory items policies
create policy "Users can view own inventory items" on inventory_items
  for select using (auth.uid() = user_id);

create policy "Users can insert own inventory items" on inventory_items
  for insert with check (auth.uid() = user_id);

create policy "Users can update own inventory items" on inventory_items
  for update using (auth.uid() = user_id);

create policy "Users can delete own inventory items" on inventory_items
  for delete using (auth.uid() = user_id);

-- Marketplace analytics policies
create policy "Users can view analytics for own items" on marketplace_analytics
  for select using (
    exists (
      select 1 from inventory_items
      where inventory_items.id = marketplace_analytics.inventory_item_id
      and inventory_items.user_id = auth.uid()
    )
  );

create policy "Users can insert analytics for own items" on marketplace_analytics
  for insert with check (
    exists (
      select 1 from inventory_items
      where inventory_items.id = marketplace_analytics.inventory_item_id
      and inventory_items.user_id = auth.uid()
    )
  );

create policy "Users can update analytics for own items" on marketplace_analytics
  for update using (
    exists (
      select 1 from inventory_items
      where inventory_items.id = marketplace_analytics.inventory_item_id
      and inventory_items.user_id = auth.uid()
    )
  );

-- Saved analyses policies
create policy "Users can view own saved analyses" on saved_analyses
  for select using (auth.uid() = user_id);

create policy "Users can insert own saved analyses" on saved_analyses
  for insert with check (auth.uid() = user_id);

create policy "Users can update own saved analyses" on saved_analyses
  for update using (auth.uid() = user_id);

create policy "Users can delete own saved analyses" on saved_analyses
  for delete using (auth.uid() = user_id);

-- Storage policies for inventory images
create policy "Users can upload inventory images" on storage.objects
  for insert with check (bucket_id = 'inventory-images' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can view inventory images" on storage.objects
  for select using (bucket_id = 'inventory-images');

create policy "Users can update own inventory images" on storage.objects
  for update using (bucket_id = 'inventory-images' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can delete own inventory images" on storage.objects
  for delete using (bucket_id = 'inventory-images' and auth.uid()::text = (storage.foldername(name))[1]);

-- Functions and triggers

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)));
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on user signup
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Function to update updated_at timestamp (if needed in future)
-- create or replace function public.handle_updated_at()
-- returns trigger as $$
-- begin
--   new.updated_at = now();
--   return new;
-- end;
-- $$ language plpgsql;

-- Indexes for performance optimization

-- Profiles indexes
create index if not exists profiles_email_idx on profiles(email);
create index if not exists profiles_username_idx on profiles(username);
create index if not exists profiles_created_at_idx on profiles(created_at);

-- Inventory items indexes
create index if not exists inventory_items_user_id_idx on inventory_items(user_id);
create index if not exists inventory_items_status_idx on inventory_items(status);
create index if not exists inventory_items_category_idx on inventory_items(category);
create index if not exists inventory_items_brand_idx on inventory_items(brand);
create index if not exists inventory_items_created_at_idx on inventory_items(created_at);
create index if not exists inventory_items_user_status_idx on inventory_items(user_id, status);
create index if not exists inventory_items_user_category_idx on inventory_items(user_id, category);

-- Marketplace analytics indexes
create index if not exists marketplace_analytics_inventory_item_id_idx on marketplace_analytics(inventory_item_id);
create index if not exists marketplace_analytics_platform_idx on marketplace_analytics(platform);
create index if not exists marketplace_analytics_created_at_idx on marketplace_analytics(created_at);
create index if not exists marketplace_analytics_item_platform_idx on marketplace_analytics(inventory_item_id, platform);

-- Saved analyses indexes
create index if not exists saved_analyses_user_id_idx on saved_analyses(user_id);
create index if not exists saved_analyses_created_at_idx on saved_analyses(created_at);

-- Enable realtime for tables that benefit from real-time updates
alter publication supabase_realtime add table inventory_items;
alter publication supabase_realtime add table marketplace_analytics;
alter publication supabase_realtime add table saved_analyses;

-- Note: profiles table typically doesn't need realtime as it's rarely updated
